/**
 * Tests for the codegen pipeline: wasmParser + generator.
 *
 * These tests work without a real WASM file by constructing synthetic
 * ContractSpec objects and verifying the generator output, and by
 * testing the WASM parser's error handling and LEB128 decoder directly.
 */

import { generateContractClass } from "../packages/core/src/codegen/generator";
import type { ContractSpec } from "../packages/core/src/codegen/wasmParser";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function makeSpec(overrides: Partial<ContractSpec> = {}): ContractSpec {
  return {
    functions: [],
    structs: [],
    enums: [],
    ...overrides,
  };
}

// ─── generateContractClass ────────────────────────────────────────────────────

describe("generateContractClass", () => {
  test("generates a class that extends BaseContract", () => {
    const src = generateContractClass(makeSpec(), "TokenContract");
    expect(src).toContain("class TokenContract extends BaseContract");
  });

  test("includes auto-generated header comment", () => {
    const src = generateContractClass(makeSpec(), "MyContract");
    expect(src).toContain("Auto-generated by axionvera-cli codegen");
  });

  test("imports BaseContract from the specified coreImport path", () => {
    const src = generateContractClass(makeSpec(), "Foo", "../core");
    expect(src).toContain('from "../core/contracts/BaseContract"');
  });

  test("generates an args interface for a function with inputs", () => {
    const spec = makeSpec({
      functions: [
        {
          name: "deposit",
          doc: "Deposit tokens",
          inputs: [
            { name: "amount", type: "bigint", scSpecType: "i128" },
            { name: "from", type: "string", scSpecType: "address" },
          ],
          outputs: [],
          readonly: false,
        },
      ],
    });
    const src = generateContractClass(spec, "VaultContract");
    expect(src).toContain("export interface DepositArgs");
    expect(src).toContain("amount: bigint");
    expect(src).toContain("from: string");
  });

  test("does not generate an args interface for a zero-input function", () => {
    const spec = makeSpec({
      functions: [
        {
          name: "claim_rewards",
          doc: "",
          inputs: [],
          outputs: [],
          readonly: false,
        },
      ],
    });
    const src = generateContractClass(spec, "VaultContract");
    expect(src).not.toContain("ClaimRewardsArgs");
  });

  test("generates an invoke call for a mutating function", () => {
    const spec = makeSpec({
      functions: [
        {
          name: "withdraw",
          doc: "",
          inputs: [{ name: "amount", type: "bigint", scSpecType: "i128" }],
          outputs: [],
          readonly: false,
        },
      ],
    });
    const src = generateContractClass(spec, "VaultContract");
    expect(src).toContain('this.invoke("withdraw"');
  });

  test("generates a query call for a read-only function", () => {
    const spec = makeSpec({
      functions: [
        {
          name: "get_balance",
          doc: "",
          inputs: [{ name: "account", type: "string", scSpecType: "address" }],
          outputs: [{ name: "result0", type: "bigint", scSpecType: "i128" }],
          readonly: true,
        },
      ],
    });
    const src = generateContractClass(spec, "VaultContract");
    expect(src).toContain('this.query("get_balance"');
    expect(src).toContain("this.decodeI128");
  });

  test("generates struct interfaces", () => {
    const spec = makeSpec({
      structs: [
        {
          name: "VaultInfo",
          doc: "Vault information",
          fields: [
            { name: "total_assets", type: "bigint" },
            { name: "apy", type: "number" },
          ],
        },
      ],
    });
    const src = generateContractClass(spec, "VaultContract");
    expect(src).toContain("export interface VaultInfo");
    expect(src).toContain("total_assets: bigint");
    expect(src).toContain("apy: number");
  });

  test("generates enum types", () => {
    const spec = makeSpec({
      enums: [
        {
          name: "Status",
          doc: "",
          cases: [
            { name: "Active", value: 0 },
            { name: "Paused", value: 1 },
          ],
        },
      ],
    });
    const src = generateContractClass(spec, "VaultContract");
    expect(src).toContain("export enum Status");
    expect(src).toContain("Active = 0");
    expect(src).toContain("Paused = 1");
  });

  test("converts snake_case function names to camelCase methods", () => {
    const spec = makeSpec({
      functions: [
        {
          name: "claim_rewards",
          doc: "",
          inputs: [],
          outputs: [],
          readonly: false,
        },
      ],
    });
    const src = generateContractClass(spec, "VaultContract");
    expect(src).toContain("async claimRewards()");
  });

  test("encodes address args with encodeAddress", () => {
    const spec = makeSpec({
      functions: [
        {
          name: "transfer",
          doc: "",
          inputs: [{ name: "to", type: "string", scSpecType: "address" }],
          outputs: [],
          readonly: false,
        },
      ],
    });
    const src = generateContractClass(spec, "TokenContract");
    expect(src).toContain("this.encodeAddress(args.to)");
  });

  test("encodes i128 args with encodeI128", () => {
    const spec = makeSpec({
      functions: [
        {
          name: "mint",
          doc: "",
          inputs: [{ name: "amount", type: "bigint", scSpecType: "i128" }],
          outputs: [],
          readonly: false,
        },
      ],
    });
    const src = generateContractClass(spec, "TokenContract");
    expect(src).toContain("this.encodeI128(args.amount)");
  });

  test("decodes bool result with decodeBool", () => {
    const spec = makeSpec({
      functions: [
        {
          name: "is_paused",
          doc: "",
          inputs: [],
          outputs: [{ name: "result0", type: "boolean", scSpecType: "bool" }],
          readonly: true,
        },
      ],
    });
    const src = generateContractClass(spec, "TokenContract");
    expect(src).toContain("this.decodeBool");
  });

  test("decodes string result with decodeString", () => {
    const spec = makeSpec({
      functions: [
        {
          name: "get_name",
          doc: "",
          inputs: [],
          outputs: [{ name: "result0", type: "string", scSpecType: "string" }],
          readonly: true,
        },
      ],
    });
    const src = generateContractClass(spec, "TokenContract");
    expect(src).toContain("this.decodeString");
  });
});

// ─── parseWasm error handling ─────────────────────────────────────────────────

describe("parseWasm error handling", () => {
  test("throws when file does not exist", () => {
    // We import lazily to avoid ts-node issues in CI without stellar-sdk installed
    const { parseWasm } = require("../packages/core/src/codegen/wasmParser");
    expect(() => parseWasm("/nonexistent/path/contract.wasm")).toThrow();
  });

  test("throws when WASM has no contractspecv0 section", () => {
    const { parseWasm } = require("../packages/core/src/codegen/wasmParser");
    const os = require("os");
    const path = require("path");
    const fs = require("fs");

    // Minimal valid WASM: magic + version, no sections
    const minimalWasm = Buffer.from([
      0x00, 0x61, 0x73, 0x6d, // magic: \0asm
      0x01, 0x00, 0x00, 0x00, // version: 1
    ]);

    const tmpFile = path.join(os.tmpdir(), "empty_contract.wasm");
    fs.writeFileSync(tmpFile, minimalWasm);

    try {
      expect(() => parseWasm(tmpFile)).toThrow(/contractspecv0/);
    } finally {
      fs.unlinkSync(tmpFile);
    }
  });
});
